# Generated by Django 2.2.5 on 2021-02-25 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('Questionaire 1', 'Mood Questionaire'), ('Questionaire 2', 'Closing Questionaire')], max_length=100)),
                ('question_section', models.CharField(max_length=255)),
                ('question_number', models.IntegerField(default=0)),
                ('prompt', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='UserMoodResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('accumulative_score', models.IntegerField(default=0)),
                ('result_category', models.CharField(max_length=50)),
                ('result_description', models.TextField(max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moodis.Profile')),
            ],
            options={
                'verbose_name': 'User Mood Result',
                'verbose_name_plural': 'User Mood Result',
            },
        ),
        migrations.CreateModel(
            name='ResponseOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moodis.Question')),
            ],
            options={
                'verbose_name': 'Response Option',
                'verbose_name_plural': 'Response Options',
            },
        ),
    ]
